# fly.toml app configuration file generated for fullstack-open-submissions-osa11-jbliog on 2025-07-12T14:44:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-open-submissions-osa11-jbliog'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
