app = "fullstack-open-submissions-osa11-cool-sea-9896"
primary_region = "arn"

[env]
  PORT = "3000"            # Express reads this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus     = 1
  memory   = "1gb"
