name: CI pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Lint code
        run: npm run lint

      - name: Build frontend bundle
        run: npm run build

      - name: Run unit & component tests
        run: npm test

      - name: Run Playwright end-to-end tests
        run: PORT=8080 npm run test:e2e

  deploy:
    needs: ci
    # run only on direct pushes to main (never on PRs)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # install the Fly.io CLI
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # build frontend so dist/ exists in the image
      - run: |
          npm ci
          npm run build

      # deploy – flyctl will read FLY_API_TOKEN from env
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
